import type { PortfolioContent } from "../types/content";

export const INITIAL_PORTFOLIO_CONTENT: PortfolioContent = {
  schemaVersion: 2,
  site: {
    title: "Sohel Islam Imran — Lead Full Stack Engineer",
    description: "Sohel Islam Imran is a Lead Full Stack Engineer at Kuno in Dhaka, building secure TypeScript products with React, backend services, data systems, and Cloudflare.",
    url: "https://sohelislamimran.com",
    locale: "en",
    theme: "systems-atlas",
  },
  identity: {
    name: "Sohel Islam Imran",
    handle: "sohelislamimran",
    role: "Lead Full Stack Engineer",
    location: "Dhaka, Bangladesh",
    timezone: "Asia/Dhaka",
    availability: "Open to thoughtful collaborations",
    email: "sohelislamimran@gmail.com",
    avatar: null,
  },
  hero: {
    eyebrow: "Lead Full Stack Engineer · Kuno",
    title: "I lead full-stack engineering for ambitious products.",
    intro: "I build secure TypeScript products across React interfaces, backend services, data systems, and delivery—from Dhaka for teams working everywhere.",
    actions: [
      { label: "Explore selected work", href: "/work" },
      { label: "Start a conversation", href: "mailto:sohelislamimran@gmail.com", external: true },
    ],
    metrics: [
      { value: "86", label: "public repositories" },
      { value: "294", label: "stars on expo-in-app-updates" },
      { value: "40.7k", label: "weekly package downloads · Aug 2026" },
      { value: "280k", label: "people reached on Stack Overflow" },
    ],
  },
  about: {
    title: "Engineering with a human center.",
    paragraphs: [
      "I work across interfaces, services, data, and delivery systems. The stack changes; the responsibility to make the next step understandable does not.",
      "My public work spans enterprise product engineering, React and React Native applications, open-source Expo modules, and tools that make development more observable.",
    ],
    facts: [
      { value: "Dhaka", label: "home base" },
      { value: "UTC+6", label: "timezone" },
    ],
  },
  experience: [
    {
      id: "kuno-lead",
      company: "Kuno",
      role: "Lead Full Stack Engineer",
      period: "Mar 2026 — present",
      summary: "Lead full-stack architecture and delivery across Kuno’s enterprise learning product, internal tooling, and platform operations.",
      highlights: [
        "Shape secure, role-aware product systems across onboarding, matching, localized experiences, and service boundaries.",
        "Connect application, CLI, infrastructure, CI/CD, observability, and release operations into a dependable delivery model.",
      ],
      technologies: ["TypeScript", "React", "TanStack", "ElysiaJS", "Bun", "PostgreSQL", "Redis"],
      current: true,
    },
    {
      id: "kuno-full-stack",
      company: "Kuno",
      role: "Full Stack Engineer",
      period: "Jan 2025 — Mar 2026",
      summary: "Built full-stack product capabilities across services, data systems, enterprise identity, and TanStack interfaces.",
      highlights: ["Delivered secure onboarding, matching, AI-assisted content, and localized product workflows."],
      technologies: ["TypeScript", "ElysiaJS", "Bun", "Drizzle", "PostgreSQL"],
    },
    {
      id: "kuno-mobile",
      company: "Kuno",
      role: "Mobile Application Developer",
      period: "Dec 2023 — Jan 2025",
      summary: "Developed mobile learning experiences and carried shared product behavior across native and web surfaces.",
      highlights: ["Built React Native and Expo product capabilities with attention to platform behavior and release quality."],
      technologies: ["React Native", "Expo", "TypeScript"],
    },
    {
      id: "tilleli",
      company: "Tilleli",
      role: "React Native Developer",
      period: "Jun 2021 — Jan 2024",
      summary: "Built and maintained mobile experiences for a language-learning product.",
      highlights: ["Delivered product features across React Native interfaces and integrations."],
      technologies: ["React Native", "TypeScript"],
    },
    {
      id: "bugfixers",
      company: "Bugfixers",
      role: "Frontend Developer",
      period: "Jul 2021 — Sep 2021",
      summary: "Contributed responsive frontend work early in my professional engineering journey.",
      highlights: ["Translated interface requirements into production web implementation."],
      technologies: ["JavaScript", "React", "CSS"],
    },
  ],
  projects: [
    {
      id: "kuno-platform",
      title: "Enterprise learning platform",
      slug: "kuno-platform",
      summary: "Turning layered learning operations into one coherent, secure product.",
      description: "Generalized public account of product architecture across identity, programs, pathways, matching, localization, and delivery.",
      year: "2023—now",
      role: "Lead full-stack engineering",
      status: "Current · details generalized",
      tags: ["Product systems", "Identity", "TypeScript", "Cloud infrastructure"],
      highlights: ["Role-aware domain behavior", "Lifecycle-wide authorization", "Actionable failure states"],
      featured: true,
    },
    {
      id: "expo-in-app-updates",
      title: "expo-in-app-updates",
      slug: "expo-in-app-updates",
      summary: "Native app-update behavior behind one compact Expo-shaped API.",
      description: "An open-source Expo module for native in-app update flows on Android and iOS.",
      year: "2024—now",
      role: "Creator and maintainer",
      status: "Maintained",
      tags: ["Expo", "React Native", "Kotlin", "Swift"],
      highlights: ["294 GitHub stars", "40,753 npm downloads in the measured Aug 19–25, 2026 week"],
      href: "https://www.npmjs.com/package/expo-in-app-updates",
      repository: "https://github.com/SohelIslamImran/expo-in-app-updates",
      featured: true,
    },
    {
      id: "ghosttime",
      title: "ghosttime",
      slug: "ghosttime",
      summary: "A customizable Ghostty-style animation for any terminal.",
      description: "A focused CLI with color selection, timers, focus-aware pause and resume, and automatic centering.",
      year: "2025—now",
      role: "Creator and maintainer",
      status: "Maintained",
      tags: ["TypeScript", "CLI", "npm"],
      highlights: ["85 GitHub stars"],
      href: "https://www.npmjs.com/package/ghosttime",
      repository: "https://github.com/SohelIslamImran/ghosttime",
      featured: true,
    },
    {
      id: "tailsync",
      title: "TailSync",
      slug: "tailsync",
      summary: "A native iOS app for syncing photos, videos, and files to personal Tailscale Taildrop devices.",
      description: "Transfers stay inside the user’s tailnet, with per-device history, duplicate prevention, retry handling, share-sheet support, and conservative deletion defaults.",
      year: "2026",
      role: "Creator",
      status: "Experimental",
      tags: ["Swift", "iOS", "PhotoKit", "Tailscale"],
      highlights: ["Private-network transfers", "Per-device delivery tracking", "Auto-delete off by default"],
      repository: "https://github.com/SohelIslamImran/TailSync",
    },
    {
      id: "android-mac-display",
      title: "Android Mac Display",
      slug: "android-mac-display",
      summary: "A wired USB path for using an Android phone as a secondary Mac display.",
      description: "A macOS menu-bar app and Android client use ADB port forwarding and local streaming, with no internet connection required.",
      year: "2025—2026",
      role: "Creator",
      status: "Prototype",
      tags: ["Swift", "macOS", "Android", "ADB", "USB"],
      highlights: ["Local-only streaming", "Automated ADB setup", "Native clients"],
      repository: "https://github.com/SohelIslamImran/AndroidMacDisplay",
    },
  ],
  capabilities: [
    { id: "product", title: "Product systems", description: "Domain modeling, secure flows, APIs, data behavior, and clear user outcomes.", tools: ["TypeScript", "React", "TanStack", "ElysiaJS", "Bun"] },
    { id: "mobile", title: "Mobile infrastructure", description: "Cross-platform product work and native integrations that respect platform behavior.", tools: ["React Native", "Expo", "Kotlin", "Swift"] },
    { id: "delivery", title: "Delivery systems", description: "Release paths that remain visible, guarded, observable, and recoverable.", tools: ["CI/CD", "Containers", "Cloud", "OIDC", "Observability"] },
  ],
  writing: [
    {
      id: "from-first-principles",
      title: "From first principles",
      excerpt: "From learning on a phone in Bangladesh to leading full-stack engineering work.",
      publishedAt: "2025-06-18",
      readingTime: "12 min",
      href: "/story",
      tags: ["Career", "Self-taught", "Bangladesh"],
    },
  ],
  contact: {
    title: "Have a complicated thing worth making clear?",
    intro: "Let’s build the useful version.",
    email: "sohelislamimran@gmail.com",
    responseTime: "Usually within two working days",
    links: [
      { label: "GitHub", href: "https://github.com/SohelIslamImran", external: true },
      { label: "LinkedIn", href: "https://www.linkedin.com/in/sohelislamimran/", external: true },
    ],
  },
  social: [
    { platform: "GitHub", label: "SohelIslamImran", href: "https://github.com/SohelIslamImran", handle: "SohelIslamImran" },
    { platform: "LinkedIn", label: "Sohel Islam Imran", href: "https://www.linkedin.com/in/sohelislamimran/", handle: "sohelislamimran" },
    { platform: "X", label: "SohelIslamImran", href: "https://x.com/SohelIslamImran", handle: "SohelIslamImran" },
    { platform: "Bluesky", label: "sohelislamimran.bsky.social", href: "https://bsky.app/profile/sohelislamimran.bsky.social", handle: "sohelislamimran.bsky.social" },
    { platform: "Facebook", label: "Sohel Islam Imran", href: "https://www.facebook.com/SohelIslamImran", handle: "SohelIslamImran" },
    { platform: "Stack Overflow", label: "Sohel Islam Imran", href: "https://stackoverflow.com/users/17672428/sohel-islam-imran" },
  ],
  profileLinks: [
    {
      id: "linkedin",
      platform: "LinkedIn",
      label: "Sohel Islam Imran",
      href: "https://www.linkedin.com/in/sohelislamimran/",
      handle: "sohelislamimran",
      description: "Experience, notes, and the work behind the work.",
      kind: "social",
      featured: true,
    },
    {
      id: "github",
      platform: "GitHub",
      label: "SohelIslamImran",
      href: "https://github.com/SohelIslamImran",
      handle: "SohelIslamImran",
      description: "Open-source packages, experiments, and current builds.",
      kind: "social",
      featured: true,
    },
    {
      id: "facebook",
      platform: "Facebook",
      label: "Sohel Islam Imran",
      href: "https://www.facebook.com/SohelIslamImran",
      handle: "SohelIslamImran",
      description: "Personal updates, milestones, and public posts.",
      kind: "social",
    },
    {
      id: "x",
      platform: "X",
      label: "@SohelIslamImran",
      href: "https://x.com/SohelIslamImran",
      handle: "SohelIslamImran",
      description: "Short engineering notes and public updates.",
      kind: "social",
    },
    {
      id: "bluesky",
      platform: "Bluesky",
      label: "sohelislamimran.bsky.social",
      href: "https://bsky.app/profile/sohelislamimran.bsky.social",
      handle: "sohelislamimran.bsky.social",
      description: "Another place I share public notes.",
      kind: "social",
    },
    {
      id: "stack-overflow",
      platform: "Stack Overflow",
      label: "Sohel Islam Imran",
      href: "https://stackoverflow.com/users/17672428/sohel-islam-imran",
      description: "Questions, answers, and practical debugging history.",
      kind: "work",
    },
    {
      id: "career-story",
      platform: "Story",
      label: "From a phone to full-stack engineering",
      href: "/story",
      description: "The longer story behind the work.",
      kind: "story",
    },
    {
      id: "email",
      platform: "Email",
      label: "sohelislamimran@gmail.com",
      href: "mailto:sohelislamimran@gmail.com",
      description: "For thoughtful collaborations and good problems.",
      kind: "contact",
      featured: true,
    },
  ],
  resume: {
    label: "Résumé",
    href: "/resume",
    updatedAt: "2026-08-27",
    summary: "Five years across enterprise B2B products, mobile applications, open source, and developer tooling.",
  },
  story: {
    eyebrow: "Personal field note / Long-form",
    title: "From a phone in Bangladesh to full-stack engineering.",
    intro: "A story about starting without a computer, learning in public, and following small evidence until it became a career.",
    quote: "The useful part of this story is not that the beginning was difficult. It is that consistency kept changing what was possible.",
    chapters: [
      { id: "00", eyebrow: "Before the first line", title: "I did not grow up around computers.", paragraphs: ["I grew up in a financially constrained family in Bangladesh. When I finished SSC in 2020, software engineering was not an obvious destination. I had no computer, no coding background, and no conventional route into the field.", "The first door opened through a phone. I learned what freelancing was and began to see that the internet could be a place where I built a future."], artifact: "A phone, a question, and no map yet." },
      { id: "01", eyebrow: "The first machine", title: "My family made a bet before there was evidence.", paragraphs: ["Buying a computer was not a casual purchase for us. My family used precious savings to make it possible.", "I joined Programming Hero’s six-month web-development course, practiced relentlessly, built projects, and helped other learners."], artifact: "Six months of practice—then the real learning began." },
      { id: "02", eyebrow: "The first proof", title: "An unpaid internship was still a doorway.", paragraphs: ["Roughly six months after the course, I earned an internship with a US-based company. It gave me a real codebase, real expectations, and responsibility to make my work useful to others.", "The years that followed were not a clean staircase. Progress looked less like a breakthrough and more like returning to the work every day."], artifact: "The first professional commit mattered more than the title." },
      { id: "03", eyebrow: "The work expands", title: "From interfaces to whole systems.", paragraphs: ["React Native taught me how decisions cross JavaScript and native boundaries. Open source taught me to design for people I would never meet. Full-stack work taught me to follow an outcome through data, services, infrastructure, and release operations.", "At Kuno, that scope kept expanding. I now lead full-stack work across product architecture, secure enterprise flows, and delivery systems."], artifact: "The stack changed. The habit of following the whole problem did not." },
      { id: "04", eyebrow: "Still in motion", title: "The destination is a larger field of view.", paragraphs: ["I want to keep building products with operational depth, maintain useful tools, mentor engineers, and work remotely while seeing more of the world.", "I started with no map. Now I build them—for products, teams, and the journeys I want to remember."], artifact: "Dhaka is the origin point, not the edge of the world." },
    ],
    sourceLabel: "Read the original LinkedIn post",
    sourceHref: "https://www.linkedin.com/posts/sohelislamimran_fromzerotoengineer-careerjourney-selftaught-activity-7341153854459125762-pW02",
  },
  travel: {
    eyebrow: "Field notes / Atlas in progress",
    title: "The world is the next system I want to understand.",
    intro: "A living record of places, conversations, small observations, and the work that travels with me. No bucket list. No invented pins.",
    origin: "Dhaka, Bangladesh",
    entries: [],
  },
  media: [],
};
