/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as FieldNotesRouteImport } from './routes/field-notes'
import { Route as LinksRouteImport } from './routes/links'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoryRouteImport } from './routes/story'
import { Route as WorkRouteImport } from './routes/work'
import { Route as LinksLinkIdRouteImport } from './routes/links/$linkId'
import { Route as MediaAssetIdRouteImport } from './routes/media/$assetId'
import { Route as ResumeEditRouteImport } from './routes/resume.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesRoute = FieldNotesRouteImport.update({
  id: '/field-notes',
  path: '/field-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksLinkIdRoute = LinksLinkIdRouteImport.update({
  id: '/$linkId',
  path: '/$linkId',
  getParentRoute: () => LinksRoute,
} as any)
const MediaAssetIdRoute = MediaAssetIdRouteImport.update({
  id: '/media/$assetId',
  path: '/media/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeEditRoute = ResumeEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ResumeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cms': typeof CmsRoute
  '/field-notes': typeof FieldNotesRoute
  '/links': typeof LinksRouteWithChildren
  '/resume': typeof ResumeRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/work': typeof WorkRoute
  '/links/$linkId': typeof LinksLinkIdRoute
  '/media/$assetId': typeof MediaAssetIdRoute
  '/resume/edit': typeof ResumeEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cms': typeof CmsRoute
  '/field-notes': typeof FieldNotesRoute
  '/links': typeof LinksRouteWithChildren
  '/resume': typeof ResumeRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/work': typeof WorkRoute
  '/links/$linkId': typeof LinksLinkIdRoute
  '/media/$assetId': typeof MediaAssetIdRoute
  '/resume/edit': typeof ResumeEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cms': typeof CmsRoute
  '/field-notes': typeof FieldNotesRoute
  '/links': typeof LinksRouteWithChildren
  '/resume': typeof ResumeRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/work': typeof WorkRoute
  '/links/$linkId': typeof LinksLinkIdRoute
  '/media/$assetId': typeof MediaAssetIdRoute
  '/resume/edit': typeof ResumeEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cms'
    | '/field-notes'
    | '/links'
    | '/resume'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/story'
    | '/work'
    | '/links/$linkId'
    | '/media/$assetId'
    | '/resume/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cms'
    | '/field-notes'
    | '/links'
    | '/resume'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/story'
    | '/work'
    | '/links/$linkId'
    | '/media/$assetId'
    | '/resume/edit'
  id:
    | '__root__'
    | '/'
    | '/cms'
    | '/field-notes'
    | '/links'
    | '/resume'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/story'
    | '/work'
    | '/links/$linkId'
    | '/media/$assetId'
    | '/resume/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CmsRoute: typeof CmsRoute
  FieldNotesRoute: typeof FieldNotesRoute
  LinksRoute: typeof LinksRouteWithChildren
  ResumeRoute: typeof ResumeRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  WorkRoute: typeof WorkRoute
  MediaAssetIdRoute: typeof MediaAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes': {
      id: '/field-notes'
      path: '/field-notes'
      fullPath: '/field-notes'
      preLoaderRoute: typeof FieldNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/$linkId': {
      id: '/links/$linkId'
      path: '/$linkId'
      fullPath: '/links/$linkId'
      preLoaderRoute: typeof LinksLinkIdRouteImport
      parentRoute: typeof LinksRoute
    }
    '/media/$assetId': {
      id: '/media/$assetId'
      path: '/media/$assetId'
      fullPath: '/media/$assetId'
      preLoaderRoute: typeof MediaAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/edit': {
      id: '/resume/edit'
      path: '/edit'
      fullPath: '/resume/edit'
      preLoaderRoute: typeof ResumeEditRouteImport
      parentRoute: typeof ResumeRoute
    }
  }
}

interface LinksRouteChildren {
  LinksLinkIdRoute: typeof LinksLinkIdRoute
}

const LinksRouteChildren: LinksRouteChildren = {
  LinksLinkIdRoute: LinksLinkIdRoute,
}

const LinksRouteWithChildren = LinksRoute._addFileChildren(LinksRouteChildren)

interface ResumeRouteChildren {
  ResumeEditRoute: typeof ResumeEditRoute
}

const ResumeRouteChildren: ResumeRouteChildren = {
  ResumeEditRoute: ResumeEditRoute,
}

const ResumeRouteWithChildren =
  ResumeRoute._addFileChildren(ResumeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmsRoute: CmsRoute,
  FieldNotesRoute: FieldNotesRoute,
  LinksRoute: LinksRouteWithChildren,
  ResumeRoute: ResumeRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  WorkRoute: WorkRoute,
  MediaAssetIdRoute: MediaAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
